package com.example.exifer.db;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * This class was autogenerated by Torque on:
 *
 * [Wed Jan 02 12:03:11 JST 2013]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Exifmap
 */
public abstract class BaseExifmap extends BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1357095791790L;

    /** The Peer class */
    private static final ExifmapPeer peer =
        new ExifmapPeer();


    /** The value for the id field */
    private int id;

    /** The value for the path field */
    private String path;

    /** The value for the name field */
    private String name;

    /** The value for the exifdate field */
    private Date exifdate;

    /** The value for the filedate field */
    private Date filedate;

    /** The value for the size field */
    private long size;

    /** The value for the ctime field */
    private Date ctime;

    /** The value for the mtime field */
    private Date mtime;


    /**
     * Get the Id
     *
     * @return int
     */
    public int getId()
    {
        return id;
    }


    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(int v) 
    {

        if (this.id != v)
        {
            this.id = v;
            setModified(true);
        }


    }

    /**
     * Get the Path
     *
     * @return String
     */
    public String getPath()
    {
        return path;
    }


    /**
     * Set the value of Path
     *
     * @param v new value
     */
    public void setPath(String v) 
    {

        if (!ObjectUtils.equals(this.path, v))
        {
            this.path = v;
            setModified(true);
        }


    }

    /**
     * Get the Name
     *
     * @return String
     */
    public String getName()
    {
        return name;
    }


    /**
     * Set the value of Name
     *
     * @param v new value
     */
    public void setName(String v) 
    {

        if (!ObjectUtils.equals(this.name, v))
        {
            this.name = v;
            setModified(true);
        }


    }

    /**
     * Get the Exifdate
     *
     * @return Date
     */
    public Date getExifdate()
    {
        return exifdate;
    }


    /**
     * Set the value of Exifdate
     *
     * @param v new value
     */
    public void setExifdate(Date v) 
    {

        if (!ObjectUtils.equals(this.exifdate, v))
        {
            this.exifdate = v;
            setModified(true);
        }


    }

    /**
     * Get the Filedate
     *
     * @return Date
     */
    public Date getFiledate()
    {
        return filedate;
    }


    /**
     * Set the value of Filedate
     *
     * @param v new value
     */
    public void setFiledate(Date v) 
    {

        if (!ObjectUtils.equals(this.filedate, v))
        {
            this.filedate = v;
            setModified(true);
        }


    }

    /**
     * Get the Size
     *
     * @return long
     */
    public long getSize()
    {
        return size;
    }


    /**
     * Set the value of Size
     *
     * @param v new value
     */
    public void setSize(long v) 
    {

        if (this.size != v)
        {
            this.size = v;
            setModified(true);
        }


    }

    /**
     * Get the Ctime
     *
     * @return Date
     */
    public Date getCtime()
    {
        return ctime;
    }


    /**
     * Set the value of Ctime
     *
     * @param v new value
     */
    public void setCtime(Date v) 
    {

        if (!ObjectUtils.equals(this.ctime, v))
        {
            this.ctime = v;
            setModified(true);
        }


    }

    /**
     * Get the Mtime
     *
     * @return Date
     */
    public Date getMtime()
    {
        return mtime;
    }


    /**
     * Set the value of Mtime
     *
     * @param v new value
     */
    public void setMtime(Date v) 
    {

        if (!ObjectUtils.equals(this.mtime, v))
        {
            this.mtime = v;
            setModified(true);
        }


    }

       
        
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
            fieldNames.add("Id");
            fieldNames.add("Path");
            fieldNames.add("Name");
            fieldNames.add("Exifdate");
            fieldNames.add("Filedate");
            fieldNames.add("Size");
            fieldNames.add("Ctime");
            fieldNames.add("Mtime");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("Id"))
        {
            return new Integer(getId());
        }
        if (name.equals("Path"))
        {
            return getPath();
        }
        if (name.equals("Name"))
        {
            return getName();
        }
        if (name.equals("Exifdate"))
        {
            return getExifdate();
        }
        if (name.equals("Filedate"))
        {
            return getFiledate();
        }
        if (name.equals("Size"))
        {
            return new Long(getSize());
        }
        if (name.equals("Ctime"))
        {
            return getCtime();
        }
        if (name.equals("Mtime"))
        {
            return getMtime();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("Id"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setId(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Path"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setPath((String) value);
            return true;
        }
        if (name.equals("Name"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setName((String) value);
            return true;
        }
        if (name.equals("Exifdate"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setExifdate((Date) value);
            return true;
        }
        if (name.equals("Filedate"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setFiledate((Date) value);
            return true;
        }
        if (name.equals("Size"))
        {
            if (value == null || ! (Long.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not a Long object.");
            }
            setSize(((Long) value).longValue());
            return true;
        }
        if (name.equals("Ctime"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setCtime((Date) value);
            return true;
        }
        if (name.equals("Mtime"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setMtime((Date) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(ExifmapPeer.ID))
        {
            return new Integer(getId());
        }
        if (name.equals(ExifmapPeer.PATH))
        {
            return getPath();
        }
        if (name.equals(ExifmapPeer.NAME))
        {
            return getName();
        }
        if (name.equals(ExifmapPeer.EXIFDATE))
        {
            return getExifdate();
        }
        if (name.equals(ExifmapPeer.FILEDATE))
        {
            return getFiledate();
        }
        if (name.equals(ExifmapPeer.SIZE))
        {
            return new Long(getSize());
        }
        if (name.equals(ExifmapPeer.CTIME))
        {
            return getCtime();
        }
        if (name.equals(ExifmapPeer.MTIME))
        {
            return getMtime();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (ExifmapPeer.ID.equals(name))
        {
            return setByName("Id", value);
        }
      if (ExifmapPeer.PATH.equals(name))
        {
            return setByName("Path", value);
        }
      if (ExifmapPeer.NAME.equals(name))
        {
            return setByName("Name", value);
        }
      if (ExifmapPeer.EXIFDATE.equals(name))
        {
            return setByName("Exifdate", value);
        }
      if (ExifmapPeer.FILEDATE.equals(name))
        {
            return setByName("Filedate", value);
        }
      if (ExifmapPeer.SIZE.equals(name))
        {
            return setByName("Size", value);
        }
      if (ExifmapPeer.CTIME.equals(name))
        {
            return setByName("Ctime", value);
        }
      if (ExifmapPeer.MTIME.equals(name))
        {
            return setByName("Mtime", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return new Integer(getId());
        }
        if (pos == 1)
        {
            return getPath();
        }
        if (pos == 2)
        {
            return getName();
        }
        if (pos == 3)
        {
            return getExifdate();
        }
        if (pos == 4)
        {
            return getFiledate();
        }
        if (pos == 5)
        {
            return new Long(getSize());
        }
        if (pos == 6)
        {
            return getCtime();
        }
        if (pos == 7)
        {
            return getMtime();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("Id", value);
        }
    if (position == 1)
        {
            return setByName("Path", value);
        }
    if (position == 2)
        {
            return setByName("Name", value);
        }
    if (position == 3)
        {
            return setByName("Exifdate", value);
        }
    if (position == 4)
        {
            return setByName("Filedate", value);
        }
    if (position == 5)
        {
            return setByName("Size", value);
        }
    if (position == 6)
        {
            return setByName("Ctime", value);
        }
    if (position == 7)
        {
            return setByName("Mtime", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(ExifmapPeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    ExifmapPeer.doInsert((Exifmap) this, con);
                    setNew(false);
                }
                else
                {
                    ExifmapPeer.doUpdate((Exifmap) this, con);
                }
            }

            alreadyInSave = false;
        }
    }


    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
        setId(((NumberKey) key).intValue());
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
        setId(Integer.parseInt(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getId());
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Exifmap copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public Exifmap copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public Exifmap copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new Exifmap(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public Exifmap copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new Exifmap(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected Exifmap copyInto(Exifmap copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected Exifmap copyInto(Exifmap copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected Exifmap copyInto(Exifmap copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setPath(path);
        copyObj.setName(name);
        copyObj.setExifdate(exifdate);
        copyObj.setFiledate(filedate);
        copyObj.setSize(size);
        copyObj.setCtime(ctime);
        copyObj.setMtime(mtime);

        copyObj.setId( 0);

        if (deepcopy)
        {
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected Exifmap copyInto(Exifmap copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setId(id);
        copyObj.setPath(path);
        copyObj.setName(name);
        copyObj.setExifdate(exifdate);
        copyObj.setFiledate(filedate);
        copyObj.setSize(size);
        copyObj.setCtime(ctime);
        copyObj.setMtime(mtime);

        copyObj.setId( 0);

        if (deepcopy)
        {
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public ExifmapPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return ExifmapPeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Exifmap:\n");
        str.append("Id = ")
           .append(getId())
           .append("\n");
        str.append("Path = ")
           .append(getPath())
           .append("\n");
        str.append("Name = ")
           .append(getName())
           .append("\n");
        str.append("Exifdate = ")
           .append(getExifdate())
           .append("\n");
        str.append("Filedate = ")
           .append(getFiledate())
           .append("\n");
        str.append("Size = ")
           .append(getSize())
           .append("\n");
        str.append("Ctime = ")
           .append(getCtime())
           .append("\n");
        str.append("Mtime = ")
           .append(getMtime())
           .append("\n");
        return(str.toString());
    }
}
