package com.example.exifer.db;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Jan 02 11:58:49 JST 2013]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Exifmap
    extends com.example.exifer.db.BaseExifmap
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1357095529173L;

}
